# Generated by Django 2.2.7 on 2019-11-20 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=50)),
                ('gift_description', models.CharField(max_length=200)),
                ('gift_photo', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(verbose_name='date gift offered')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(verbose_name='date match made')),
                ('date_sent', models.DateField(verbose_name='date gift posted')),
                ('gift_status', models.CharField(max_length=50)),
                ('thank_you_message', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=None, null=True)),
                ('gift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sista_regifta.Gift')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_swaps', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_swaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
