# Generated by Django 2.2.7 on 2019-11-23 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sista_regifta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date gift offered'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_photo',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
