# Generated by Django 2.2.7 on 2019-12-03 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sista_regifta', '0003_auto_20191123_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='gift_waiting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
