# Generated by Django 2.2.7 on 2019-12-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sista_regifta', '0004_auto_20191203_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='date_sent',
            field=models.DateField(blank=True, null=True, verbose_name='date gift sent'),
        ),
        migrations.AlterField(
            model_name='swap',
            name='match_date',
            field=models.DateField(blank=True, null=True, verbose_name='date match made'),
        ),
    ]
