# Generated by Django 2.2.7 on 2019-12-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sista_regifta', '0005_auto_20191203_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='thank_you_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
