# Generated by Django 2.2.7 on 2019-12-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sista_regifta', '0006_auto_20191203_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_waiting',
            field=models.BooleanField(default=True, verbose_name='gift not yet matched'),
        ),
    ]
