# Generated by Django 2.2.7 on 2019-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sista_regifta', '0007_auto_20191206_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
